//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomadoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calificacion
    {
        public int CalificacionID { get; set; }
        public double Calificacion1 { get; set; }
        public double Calificacion2 { get; set; }
        public double Calificacion3 { get; set; }
        public double Calificacion4 { get; set; }
        public double Calificacion_Final { get; set; }
        public int IncripcionCursoID { get; set; }
        public int AsignaturaID { get; set; }
    
        public virtual Asignatura Asignatura { get; set; }
        public virtual IncripcionCurso IncripcionCurso { get; set; }
    }
}
