//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiplomadoFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Usuario()
        {
            this.IncripcionCurso = new HashSet<IncripcionCurso>();
        }
    
        public int UsuarioID { get; set; }
        public string Nombres { get; set; }
        public string Apellidos { get; set; }
        public int SexoID { get; set; }
        public System.DateTime Nacimiento { get; set; }
        public string Nombre_Usuaro { get; set; }
        public string Clave { get; set; }
        public int PerfilID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncripcionCurso> IncripcionCurso { get; set; }
        public virtual Perfil Perfil { get; set; }
        public virtual Sexo Sexo { get; set; }
    }
}
